export const SEALED_RECORD_ALGORITHM = "AES-256-GCM" as const
export const SEALED_RECORD_WEB_CRYPTO_ALGORITHM = "AES-GCM"
export const SEALED_RECORD_KEY_VERSION = 1
export const SEALED_RECORD_KEY_LENGTH_BYTES = 32
export const SEALED_RECORD_NONCE_LENGTH_BYTES = 12
