export const REALTIME_SESSION_REVALIDATION_INTERVAL_MS = 60 * 1000
export const AUTH_ACTIVITY_TOUCH_INTERVAL_MS = 7 * 24 * 60 * 60 * 1_000

export const D1_SESSION_COOKIE_NAME = "lynvo_session"
export const D1_SESSION_TOTAL_DURATION_MS = 365 * 24 * 60 * 60 * 1_000
export const D1_SESSION_COOKIE_MAX_AGE_SECONDS =
  D1_SESSION_TOTAL_DURATION_MS / 1_000
export const SESSION_SWEEP_BATCH_SIZE = 200
export const SESSION_DEVICE_NAME_MAX_LENGTH = 80

export const GOOGLE_OAUTH_STATE_COOKIE_NAME = "lynvo_oauth_state"
export const GOOGLE_OAUTH_STATE_TTL_MS = 10 * 60 * 1_000
export const GOOGLE_OAUTH_CODE_VERIFIER_BYTES = 32
export const GOOGLE_OAUTH_STATE_BYTES = 32
export const GOOGLE_OAUTH_TOKEN_TIMEOUT_MS = 10 * 1_000
export const GOOGLE_OAUTH_AUTH_ENDPOINT =
  "https://accounts.google.com/o/oauth2/v2/auth"
export const GOOGLE_OAUTH_TOKEN_ENDPOINT = "https://oauth2.googleapis.com/token"
export const GOOGLE_OAUTH_SCOPE = "openid email profile"
export const GOOGLE_OAUTH_ISSUERS = [
  "https://accounts.google.com",
  "accounts.google.com",
]

export const DEVICE_CODE_TTL_MS = 10 * 60 * 1000
export const DEVICE_CODE_EXCHANGE_LEASE_MS = 60 * 1000
export const DEVICE_CODE_CLEANUP_BATCH_SIZE = 100
export const DEVICE_CODE_LETTER_COUNT = 8
export const DEVICE_CODE_GROUP_LENGTH = 4
export const DEVICE_CODE_ALPHABET_SIZE = 26
export const DEVICE_CODE_FIRST_LETTER_CODE_POINT = "A".charCodeAt(0)
export const DEVICE_CODE_RANDOM_LIMIT =
  Math.floor(256 / DEVICE_CODE_ALPHABET_SIZE) * DEVICE_CODE_ALPHABET_SIZE
export const DEVICE_CODE_COLLISION_ATTEMPTS = 5
export const DEVICE_POLL_RATE_LIMIT = 120
export const DEVICE_POLL_RATE_WINDOW_SECONDS = 60
export const DEVICE_CODE_CREATION_RATE_LIMIT = 5
export const DEVICE_CODE_CREATION_RATE_WINDOW_SECONDS = 10 * 60
export const EXTRACTION_ROUTE_RATE_LIMIT = 30
export const EXTRACTION_ROUTE_RATE_WINDOW_SECONDS = 60

export const DAY_MS = 24 * 60 * 60 * 1_000
export const SECOND_MS = 1_000
export const USER_STORAGE_LIMIT_BYTES = 3 * 1024 * 1024
export const USER_STORAGE_WARNING_BYTES = Math.round(
  0.8 * USER_STORAGE_LIMIT_BYTES
)
export const CUSTOM_PLUGIN_SERVER_REGISTRATION_LIMIT = 5
export const PLUGIN_SERVER_DEPENDENT_DELETE_LIMIT = 100
export const PLUGIN_SERVER_REGISTRATION_TTL_MS = 10 * 60 * 1_000
export const LINK_LIMIT_BYTES = 256 * 1024
export const LINKS_MAX_COUNT = 1_000
export const STORAGE_LEDGER_SCHEMA_VERSION = 2
export const STORAGE_RECONSTRUCTION_DOCUMENT_LIMIT = 1_000
export const LINK_RETENTION_BATCH_SIZE = 50
export const DEFAULT_RETENTION_DAYS = 30
export const MAX_RETENTION_DAYS = 30
export const STORAGE_RETENTION_DAY_OPTIONS = [7, 15, 30]
export const ACCOUNT_ERASURE_BATCH_SIZE = 50
export const ACCOUNT_ERASURE_MAX_STEPS_PER_RUN = 500
export const USER_DAILY_LYNVO_PLUGIN_EXTRACTION_LIMIT = 30
export const GLOBAL_DAILY_LYNVO_PLUGIN_EXTRACTION_LIMIT = 20_000
export const USER_MONTHLY_LYNVO_PLUGIN_EXTRACTION_LIMIT = 200
export const MANAGED_EXTRACTION_RESERVATION_LEASE_MS = 5 * 60 * 1000
export const MANAGED_EXTRACTION_RECOVERY_BATCH_SIZE = 100
export const LINK_EXTRACTION_BATCH_SIZE = 3
export const PLUGIN_SERVER_MANIFEST_REFRESH_INTERVAL_MS = 6 * 60 * 60 * 1000
export const PLUGIN_SERVER_MANIFEST_REFRESH_RETRY_DOWN_INTERVAL_MS =
  60 * 60 * 1000
export const PLUGIN_SERVER_MANIFEST_REFRESH_BATCH_SIZE = 20
export const PLUGIN_SERVER_PROXY_BALANCE_REFRESH_INTERVAL_MS =
  6 * 60 * 60 * 1000
export const LINK_EXTRACTION_LEASE_MS = 5 * 60 * 1000
export const LINK_EXTRACTION_MAX_ATTEMPTS = 10
export const LINK_EXTRACTION_MAX_PENDING_RETRY_SECONDS = 600
export const MEDIA_METADATA_REQUEST_TIMEOUT_MS = 8 * 1000
export const MEDIA_METADATA_REQUEST_ATTEMPTS = 3
export const MEDIA_METADATA_REQUEST_RETRY_DELAY_MS = 2 * 1000
export const MEDIA_ARTWORK_REQUEST_BATCH_LIMIT = 12
export const REMOTE_COMMAND_TTL_MS = 5 * 60 * 1000
export const REMOTE_COMMAND_CLAIM_LEASE_MS = 30 * 1000
export const REMOTE_COMMAND_MAX_PAYLOAD_BYTES = 16 * 1024
export const REMOTE_COMMAND_QUERY_LIMIT = 100
export const REMOTE_COMMAND_NOTIFICATION_BATCH_SIZE = 100
export const REMOTE_COMMAND_CLEANUP_BATCH_SIZE = 100
export const SAVED_LINK_COMMAND_OPERATION_TTL_MS = DAY_MS
export const SAVED_LINK_COMMAND_OPERATION_CLEANUP_BATCH_SIZE = 100
export const SAVED_LINK_OPTIMISTIC_RETRY_ATTEMPTS = 2
export const PLUGIN_SERVER_REGISTRATION_SWEEP_BATCH_SIZE = 100
export const RETENTION_SWEEP_MAX_BATCHES_PER_RUN = 200
export const EMPTY_LINK_METADATA_JSON = JSON.stringify({
  schemaVersion: 3,
  source: {},
  extraction: { extractedLinks: [] },
  playback: { openedUrls: [], resolvedMirrors: {} },
})
export { DATA_VERSION_RESPONSE_HEADER } from "../app/lib/constants"

export const CRON_SCHEDULE_HOURLY_MAINTENANCE = "9 * * * *"
export const CRON_SCHEDULE_DAILY_RETENTION = "41 3 * * *"
