export const WORKER_SESSION_COOKIE_NAME = "__Host-lynvo-session"
export const PLUGIN_SERVER_INTERNAL_ORIGIN = "https://plugin-server.internal"
export const PLUGIN_SERVER_REQUEST_TIMEOUT_MS = 50_000
export const OUTBOUND_HTTP_MAX_REDIRECTS = 3
export const OUTBOUND_HTTP_MAX_RESPONSE_BYTES = 5 * 1024 * 1024
export const OUTBOUND_HTTP_TIMEOUT_MS = 15_000
export const LYNVO_PLUGIN_SERVER_ID = "lynvo:dev.lynvo.plugin-server"
export const COOKIE_PREFERENCES_STORAGE_KEY = "lynvo:cookie-preferences"
export const COOKIE_PREFERENCES_VERSION = 1
export const OPEN_COOKIE_PREFERENCES_EVENT = "lynvo:open-cookie-preferences"
export const DOCS_SCROLL_OFFSET_PX = 112
export const DOCS_SCROLL_END_TOLERANCE_PX = 2
export const DEVICE_AUTH_STATUS_POLL_INTERVAL_MS = 2_000
export const MILLISECONDS_PER_SECOND = 1_000
