export const AUTH_JWT_COOKIE_NAME = "__convexAuthJWT_lynvo"
export const AUTH_REFRESH_COOKIE_NAME = "__convexAuthRefreshToken_lynvo"
export const AUTH_SESSION_MAX_AGE_SECONDS = 60 * 60 * 24 * 365
export const AUTH_SESSION_COOKIE_NAME = AUTH_JWT_COOKIE_NAME
export const AUTH_TRANSACTION_COOKIE_NAME = "auth-transaction"
export const AUTH_TRANSACTION_MAX_AGE_SECONDS = 60 * 10
export const LOCAL_CONVEX_URL = "http://127.0.0.1:3210"
export const EXTRACTOR_INTERNAL_ORIGIN = "https://extractor.internal"
export const EXTRACTOR_REQUEST_TIMEOUT_MS = 10_000
export const OFFICIAL_EXTRACTOR_ID = "official:dev.lynvo.official-extractor"
